# EDA Indicateur 1

In [1]:
import pandas as pd

df = pd.read_parquet(r"./raw/eclairage-public.parquet")
df.head(10)

,cod_ouvrag,foyer,lib_domain,lib_ouvrag,observatio,posx_ouvra,posy_ouvra,x_wgs84,y_wgs84,lib_regime,...,lampe_classe,lampe_volt,lampe_temperature_couleur,lampe_fournisseur,lampe_gradation,lum_ulor,lum_dlor,date_maj,insertion_date,geo_point_2d
0,801677,0109124,Eclairage Public,Projecteur,+9761,652176.0385610145,6862624.529103298,2.3481407998068904,48.86187754977603,24/24 (OU CIRC/NUIT/1/1BIS),...,Toute Position,230.0,4000.0,PHILIPS,None,None,None,2026-04-28,2026-04-29 08:01:37.776000,"b'\x01\x01\x00\x00\x00M\x97,\x0b\xfe\xc8\x02@\..."
1,801679,0109137,Eclairage Public,Projecteur,+9763,652162.4615239749,6862622.18956036,2.3479560112423616,48.861855502485746,24/24 (OU CIRC/NUIT/1/1BIS),...,Toute Position,230.0,4000.0,PHILIPS,None,0.0,80.0,2026-04-28,2026-04-29 08:01:37.776000,b'\x01\x01\x00\x00\x00D\xdcE)\x9d\xc8\x02@\xe7...
2,801683,0109121,Eclairage Public,Projecteur,+9767,652151.0983611441,6862597.60658201,2.347803901536252,48.86163358724305,24/24 (OU CIRC/NUIT/1/1BIS),...,Toute Position,230.0,4000.0,PHILIPS,None,0.0,80.0,2026-04-28,2026-04-29 08:01:37.776000,"b""\x01\x01\x00\x00\x00\xbf'tiM\xc8\x02@\n,g\x0..."
3,802025,0109752,Eclairage Public,Sol,+9791,651971.4684835963,6862563.395593197,2.3453594656792625,48.86131256484557,24/24 (OU CIRC/NUIT/1/1BIS),...,Toute Position,24.0,None,COMATELEC,None,0.0,100.0,2026-04-28,2026-04-29 08:01:37.776000,b'\x01\x01\x00\x00\x00\xd8\xa6\xd3\xd2K\xc3\x0...
4,802034,0109734,Eclairage Public,Sol,+9800,651916.1155856904,6862629.940121972,2.3445974986474267,48.86190686104774,24/24 (OU CIRC/NUIT/1/1BIS),...,Toute Position,24.0,None,COMATELEC,None,0.0,100.0,2026-04-28,2026-04-29 08:01:37.776000,b'\x01\x01\x00\x00\x00\xf6\xcaWU\xbc\xc1\x02@\...
5,802038,0109726,Eclairage Public,Sol,+9804,651887.8432494653,6862660.110204046,2.344208737925432,48.86217606523326,24/24 (OU CIRC/NUIT/1/1BIS),...,Toute Position,24.0,None,COMATELEC,None,0.0,100.0,2026-04-28,2026-04-29 08:01:37.776000,b'\x01\x01\x00\x00\x00\xea\x18\xc3\x82\xf0\xc0...
6,801778,0109194,Eclairage Public,Projecteur,+9831,652174.5903867995,6862752.555542246,2.348106655178252,48.863028765476685,24/24 (OU CIRC/NUIT/1/1BIS),...,Toute Position,230.0,4000.0,PHILIPS,None,0.0,80.0,2026-04-28,2026-04-29 08:01:37.776000,b'\x01\x01\x00\x00\x00\x97\x15\\$\xec\xc8\x02@...
7,801799,0109219,Eclairage Public,Projecteur,+9846,652155.0787462852,6862788.322301323,2.347836683683482,48.86334896161267,24/24 (OU CIRC/NUIT/1/1BIS),...,Toute Position,230.0,4000.0,PHILIPS,None,None,None,2026-04-28,2026-04-29 08:01:37.776000,b'\x01\x01\x00\x00\x00?(f\x99^\xc8\x02@\xbc\x9...
8,801799,0109218,Eclairage Public,Projecteur,+9846,652155.0787462852,6862788.322301323,2.347836683683482,48.86334896161267,24/24 (OU CIRC/NUIT/1/1BIS),...,Toute Position,230.0,4000.0,PHILIPS,None,0.0,80.0,2026-04-28,2026-04-29 08:01:37.776000,b'\x01\x01\x00\x00\x00?(f\x99^\xc8\x02@\xbc\x9...
9,802491,0109439,Eclairage Public,Projecteur,+9853,651989.4193657356,6862527.367670334,2.3456081989358917,48.860989908779,24/24 (OU CIRC/NUIT/1/1BIS),...,Toute Position,230.0,2000.0,PHILIPS,None,0.0,77.0,2026-04-28,2026-04-29 08:01:37.776000,"b""\x01\x01\x00\x00\x00\xdfE=;\xce\xc3\x02@'2\x..."

In [2]:
df = pd.read_parquet(r"./raw/ilots-de-fraicheur-equipements-activites.parquet")
df.head(10)

,identifiant,id_dicom,nom,type,payant,adresse,arrondissement,statut_ouverture,horaires_periode,horaires_lundi,horaires_mardi,horaires_mercredi,horaires_jeudi,horaires_vendredi,horaires_samedi,horaires_dimanche,geo_shape,geo_point_2d,proposition_usager
0,LC35,19465,Eglise Saint-François de Sales,Lieux de culte,Non,15 RUE AMPERE,75017,NaN,"Les horaires étant susceptibles d'évoluer, mer...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,b'\x01\x01\x00\x00\x00\x87\x0c\x17!\xabp\x02@\...,b'\x01\x01\x00\x00\x00\x87\x0c\x17!\xabp\x02@\...,Non
1,OM50,NaN,KIOSQUE A MUSIQUE SQUARE JEAN CHERIOUX,Ombrière pérenne,Non,260 RUE DE VAUGIRARD,75015,NaN,Horaires d'ouverture de l'espace vert,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"b""\x01\x01\x00\x00\x00_\xad4\x80\x9ag\x02@\xbc...","b""\x01\x01\x00\x00\x00_\xad4\x80\x9ag\x02@\xbc...",Non
2,LC96,19484,Eglise Saint-Julien Le Pauvre,Lieux de culte,Non,1 RUE SAINT-JULIEN LE PAUVRE,75005,NaN,"Les horaires étant susceptibles d'évoluer, mer...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,b'\x01\x01\x00\x00\x00\xa8\xfad \xc6\xc6\x02@\...,b'\x01\x01\x00\x00\x00\xa8\xfad \xc6\xc6\x02@\...,Non
3,LC100,NaN,Cathedrale Saint-Vladimir Le Grand,Lieux de culte,Non,51 RUE SAINTS-PERES,75006,NaN,"Les horaires étant susceptibles d'évoluer, mer...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,b'\x01\x01\x00\x00\x00\xc15\x0e\xc2\xd2\xa5\x0...,b'\x01\x01\x00\x00\x00\xc15\x0e\xc2\xd2\xa5\x0...,Non
4,MU74,NaN,Maison du Japon,Musée,Oui,101Bis Quai Branly,75015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b'\x01\x01\x00\x00\x00\xc6\x9e\x00=tQ\x02@\x9d...,b'\x01\x01\x00\x00\x00\xc6\x9e\x00=tQ\x02@\x9d...,Non
5,MA5,(3717),MAIRIE DU 5E,Mairie d'arrondissement,Non,21 PLACE DU PANTHEON,75005,NaN,NaN,14h - 17h,14h - 17h,14h - 17h,14h - 17h,14h - 17h,14h - 17h,14h - 17h,b'\x01\x01\x00\x00\x00TT\x05\xbc\xb0\xc1\x02@\...,b'\x01\x01\x00\x00\x00TT\x05\xbc\xb0\xc1\x02@\...,Non
6,LC53,NaN,Eglise de l'Hôpital du Val de Grace,Lieux de culte,Oui,1 Place Alphonse Laveran,75005,NaN,"Les horaires étant susceptibles d'évoluer, mer...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,b'\x01\x01\x00\x00\x00\x1e\xe1\x14\x97\xfb\xbb...,b'\x01\x01\x00\x00\x00\x1e\xe1\x14\x97\xfb\xbb...,Non
7,MU10,NaN,Musée du Louvre,Musée,Oui,Rue de Rivoli,75001,NaN,NaN,09:00 - 18:00,Fermé,09:00 - 18:00,09:00 - 18:00,09:00 - 18:00,09:00 - 18:00,09:00 - 18:00,b'\x01\x01\x00\x00\x00v\x1dkYS\xb1\x02@\x8f|\x...,b'\x01\x01\x00\x00\x00v\x1dkYS\xb1\x02@\x8f|\x...,Non
8,LC12,NaN,Eglise Armenienne Saint-Jean Baptiste,Lieux de culte,Non,15 RUE JEAN GOUJON,75008,NaN,"Les horaires étant susceptibles d'évoluer, mer...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,b'\x01\x01\x00\x00\x00f\x05#i\xdct\x02@\x0ff\x...,b'\x01\x01\x00\x00\x00f\x05#i\xdct\x02@\x0ff\x...,Non
9,MU25,NaN,Musée National Guimet (annexe),Musée,Oui,6 PLACE D'IENA,75016,NaN,NaN,NaN,10:00 - 18:00,Fermé,10:00 - 18:00,10:00 - 18:00,10:00 - 18:00,10:00 - 18:00,b'\x01\x01\x00\x00\x00=K\xe5\xf0\xb4Z\x02@\x08...,b'\x01\x01\x00\x00\x00=K\xe5\xf0\xb4Z\x02@\x08...,Non

In [3]:
df = pd.read_parquet(r"./raw/ilots-de-fraicheur-espaces-verts-frais.parquet")
df.head(10)

,identifiant,nsq_espace_vert,nom,type,p_vegetation_h,proportion_vegetation_haute,adresse,arrondissement,statut_ouverture,ouvert_24h,...,horaires_vendredi,horaires_samedi,horaires_dimanche,categorie,proposition_usager,id_dicom,geo_shape,geo_point_2d,surf_veget_sup8m_2024,indice_veget_sup8m_2024
0,ID1598,12950.0,JARDINIERES DU BOULEVARD BOURDON,Décorations sur la voie publique,0.400000,40.000000,2 BOULEVARD BOURDON,75004,NaN,Oui,...,NaN,NaN,NaN,Jardiniere,NaN,NaN,b'\x01\x06\x00\x00\x00 \x00\x00\x00\x01\x03\x0...,b'\x01\x01\x00\x00\x00\xdf;\x1btA\xef\x02@f\xa...,624.205223,0.400000
1,ID827,NaN,Jardin de la place Mohamed Bouazizi,Promenades ouvertes,0.700000,70.000000,place Mohamed Bouazizi,75014,NaN,Oui,...,NaN,NaN,NaN,NaN,NaN,NaN,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\x0f\x00...,b'\x01\x01\x00\x00\x00\x7f\xbfX2f\xb3\x02@\xc5...,120.179045,0.700000
2,ID681,147.0,MAIL PIERRE DESPROGES DIT TROTTOIR PIERRE DESP...,Promenades ouvertes,0.685502,68.550155,143 RUE DE LA ROQUETTE,75011,NaN,Oui,...,NaN,NaN,NaN,Mail,NaN,NaN,b'\x01\x06\x00\x00\x00\x02\x00\x00\x00\x01\x03...,b'\x01\x01\x00\x00\x00q.\xe4D\xda\x14\x03@\xc6...,522.406493,0.408195
3,ID733,664.0,MAIL MARCEL ACHARD,Promenades ouvertes,0.382438,38.243819,6 PL MARCEL ACHARD,75019,NaN,Non,...,NaN,NaN,NaN,Mail,NaN,NaN,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00 \x00\x0...,b'\x01\x01\x00\x00\x00x\x19\xfeXs\x03\x03@\xe9...,1914.907047,0.444426
4,ID1211,10045.0,Bois de Boulogne,Bois,0.822828,82.282848,NaN,75016,NaN,Non,...,00h00 - 23h59,00h00 - 23h59,00h00 - 23h59,Bois,NaN,2779,b'\x01\x06\x00\x00\x00\t\x00\x00\x00\x01\x03\x...,b'\x01\x01\x00\x00\x00\x10\xab\xaf\xf8{%\x02@\...,153846.532000,0.630035
5,ID745,374.0,PROMENADE D'AUSTRALIE 15E,Promenades ouvertes,0.115169,11.516945,74 QUAI BRANLY,75015,NaN,Oui,...,NaN,NaN,NaN,Promenade,NaN,NaN,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\xc7\x00...,b'\x01\x01\x00\x00\x00L\xde)HQQ\x02@!\xc3\xdeY...,1750.368973,0.216565
6,ID843,827.0,SQUARE RESTIF DE LA BRETONNE,Promenades ouvertes,0.529956,52.995639,2 RUE BUCHERIE,75005,NaN,Non,...,NaN,NaN,NaN,Square,NaN,NaN,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\x14\x00...,b'\x01\x01\x00\x00\x00{\xaf\xfe\xe1R\xcb\x02@\...,29.161931,0.554146
7,ID910,11513.0,PARC DE LA VILLETTE,Jardins d'Etat,0.266145,26.614466,211 AVENUE JEAN JAURES,75019,NaN,Oui,...,00h00 - 23h59,00h00 - 23h59,00h00 - 23h59,NaN,NaN,1809,b'\x01\x06\x00\x00\x00\x04\x00\x00\x00\x01\x03...,b'\x01\x01\x00\x00\x00\x85\xd8\xa7\x04\x89\x1e...,89062.275450,0.334295
8,ID835,10045.0,La Garde Républicaine,Bois,0.313282,31.328162,93 w Avenue de l'Hippodrome,75016,NaN,Non,...,NaN,NaN,NaN,Bois,NaN,NaN,b'\x01\x06\x00\x00\x00\x01\x00\x00\x00\x01\x03...,b'\x01\x01\x00\x00\x00t\x9d\xde\xa0u\t\x02@?-\...,932.190193,0.304437
9,ID163,849.0,JARDINET DE LA PLACE RAOUL FOLLEREAU,Jardinets décoratifs,0.271363,27.136291,2 PLACE RAOUL FOLLEREAU,75010,NaN,Non,...,NaN,NaN,NaN,Jardinet,NaN,NaN,b'\x01\x06\x00\x00\x00\r\x00\x00\x00\x01\x03\x...,b'\x01\x01\x00\x00\x00\x82~\xf6\n\x10\xe9\x02@...,248.265551,0.254253

In [4]:
df = pd.read_parquet(r"./raw/les-arbres.parquet")
df.head(10)

,idbase,typeemplacement,domanialite,arrondissement,complementadresse,adresse,idemplacement,libellefrancais,genre,espece,varieteoucultivar,circonferenceencm,hauteurenm,stadedeveloppement,remarquable,geo_point_2d
0,126117,Arbre,Jardin,PARIS 20E ARRDT,NaN,JARDIN DE LA GARE DE CHARONNE / 59 BOULEVARD D...,000103036,Cèdre,Cedrus,atlantica,NaN,130,15,Adulte,NON,b'\x01\x01\x00\x00\x00\xc1\xc1\xb1d\xafF\x03@T...
1,141306,Arbre,CIMETIERE,PARIS 15E ARRDT,NaN,CIMETIERE DE VAUGIRARD / AVENUE PRINCIPALE / D...,A14000011002,Erable,Acer,platanoides,NaN,75,8,Adulte,NON,b'\x01\x01\x00\x00\x00P\x0f\xf1[\xb6F\x02@\xe5...
2,250335,Arbre,Alignement,PARIS 19E ARRDT,NaN,RUE MANIN,001002013,Platane,Platanus,x hispanica,NaN,120,20,Adulte,NON,b'\x01\x01\x00\x00\x00\x8e+\xa1)\x91\x1e\x03@\...
3,278516,Arbre,Alignement,PARIS 13E ARRDT,NaN,BOULEVARD KELLERMANN,000202013,Marronnier,Aesculus,x carnea,''Briotii'',115,10,Adulte,NON,b'\x01\x01\x00\x00\x00\xda3\xc2\xa1\xd1\xdc\x0...
4,216594,Arbre,Alignement,PARIS 19E ARRDT,15,AVENUE DE LAUMIERE,000101011,Paulownia,Paulownia,tomentosa,NaN,60,8,Jeune (arbre),NON,b'\x01\x01\x00\x00\x00\xcf\x0b\xb4\xac\xe7\x0b...
5,223855,Arbre,Alignement,PARIS 11E ARRDT,116,BOULEVARD RICHARD LENOIR,000704007,Platane,Platanus,x hispanica,NaN,30,6,Jeune (arbre),NON,b'\x01\x01\x00\x00\x00\xcb;\x10I`\xf7\x02@\xf2...
6,106474,Arbre,Jardin,PARIS 7E ARRDT,Canton 10,JARDIN DU CHAMP DE MARS ET PELOUSES DE L ECOLE...,A01002004,Platane,Platanus,x hispanica,NaN,95,12,Adulte,NON,b'\x01\x01\x00\x00\x00\x1a\x8c\xce\xdf\xd0f\x0...
7,266201,Arbre,Alignement,PARIS 15E ARRDT,111,BOULEVARD LEFEBVRE,000701006,Platane,Platanus,x hispanica,NaN,110,15,Adulte,NON,b'\x01\x01\x00\x00\x00\xf0\xecd\xf3y`\x02@\x04...
8,157556,Arbre,CIMETIERE,VAL-DE-MARNE,NaN,CIMETIERE DE THIAIS / AVENUE I / DIV 91,A12100091008,Frêne à fleurs,Fraxinus,ornus,NaN,20,5,NaN,NON,b'\x01\x01\x00\x00\x00\xa6v\xc7\x83\x1b\x00\x0...
9,105989,Arbre,Jardin,PARIS 20E ARRDT,NaN,SQUARE SEVERINE / 1 RUE LE VAU,000202022,Sequoia,Sequoiadendron,giganteum,NaN,215,15,Adulte,NON,b'\x01\x01\x00\x00\x00\xa7\x86t\xf5\xceE\x03@\...

In [5]:
df = pd.read_parquet(r"./raw/sanisettesparis.parquet")
df.head(10)

,type,statut,adresse,arrondissement,horaire,acces_pmr,relais_bebe,url_fiche_equipement,geo_shape,geo_point_2d
0,WC,Hors service,2 quai de l archeveche,75004,Horaires du parc,Non,Non,https://www.paris.fr/lieux/square-jean-xxiii-35,b'\x01\x01\x00\x00\x00{\x96^\xd0\xfa\xce\x02@\...,b'\x01\x01\x00\x00\x00{\x96^\xd0\xfa\xce\x02@\...
1,Sanisette,En service,36 bd de sebastopol,75004,06h00 - 22h00,Oui,Non,NaN,b'\x01\x01\x00\x00\x00v\x8a\x9f\xac\xdf\xcc\x0...,b'\x01\x01\x00\x00\x00v\x8a\x9f\xac\xdf\xcc\x0...
2,Sanisette,En service,10 avenue de l observatoire,75006,Horaires du parc,Oui,Non,https://www.paris.fr/lieux/jardin-des-grands-e...,b'\x01\x01\x00\x00\x00pv^\xb5\xb5\xb2\x02@\xfd...,b'\x01\x01\x00\x00\x00pv^\xb5\xb5\xb2\x02@\xfd...
3,Sanisette,En service,93b bd du montparnasse,75006,06h00 - 22h00,Non,Non,NaN,"b'\x01\x01\x00\x00\x00 ""\xea\xd5\xe3\x9e\x02@\...","b'\x01\x01\x00\x00\x00 ""\xea\xd5\xe3\x9e\x02@\..."
4,Sanisette,En service,135b bd du montparnasse,75006,06h00 - 22h00,Oui,Non,NaN,b'\x01\x01\x00\x00\x00c\x0e/\xa4\xa7\xa8\x02@0...,b'\x01\x01\x00\x00\x00c\x0e/\xa4\xa7\xa8\x02@0...
5,Sanisette,En service,2t pl joffre,75007,24/24h,Oui,Non,NaN,b'\x01\x01\x00\x00\x00\x92y\xb3\xfc\xdcp\x02@?...,b'\x01\x01\x00\x00\x00\x92y\xb3\xfc\xdcp\x02@?...
6,Sanisette,En service,1 av de verdun,75010,24/24h,Oui,Non,NaN,"b""\x01\x01\x00\x00\x00a\xba\x8bA'\xe4\x02@\x9e...","b""\x01\x01\x00\x00\x00a\xba\x8bA'\xe4\x02@\x9e..."
7,Sanisette,En service,81b bd de la villette,75010,06h00 - 22h00,Oui,Non,NaN,b'\x01\x01\x00\x00\x00\xc7\xca3\xbd\x8b\xf7\x0...,b'\x01\x01\x00\x00\x00\xc7\xca3\xbd\x8b\xf7\x0...
8,Sanisette,En service,96 rue oberkampf,75011,06h00 - 22h00,Oui,Non,NaN,b'\x01\x01\x00\x00\x00\x9fN\xf4\xf6Y\x05\x03@>...,b'\x01\x01\x00\x00\x00\x9fN\xf4\xf6Y\x05\x03@>...
9,WC,En service,30 rue du rendez-vous,75012,Horaires du parc,Oui,Non,https://www.paris.fr/lieux/jardin-debergue-ren...,"b'\x01\x01\x00\x00\x00,7\x98\xba5;\x03@eb_v\\lH@'","b'\x01\x01\x00\x00\x00,7\x98\xba5;\x03@eb_v\\lH@'"

In [6]:
df = pd.read_parquet(r"./raw/zones-touristiques-internationales.parquet")
df.head(10)

,name,type,_timestamp,_uid,source,_user,_version,boundary,_changeset,_id,geo_point_2d,geo_shape
0,Saint-Honoré - Vendôme,boundary,2016-07-26T17:22:16Z,158826,JORFTEXT000031223603,cquest,1,tourist_zone,41043008,relation/6439132,b'\x01\x01\x00\x00\x00JM\x0c\x0c\x80\xa7\x02@\...,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00d\x00\x0...
1,Montmartre,boundary,2016-07-26T16:15:57Z,158826,JORFTEXT000031223591,cquest,1,tourist_zone,41041604,relation/6438767,b'\x01\x01\x00\x00\x00\xec\xf38C\x97\xb5\x02@\...,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00H\x00\x0...
2,Olympiades,boundary,2016-07-26T16:39:02Z,158826,JORFTEXT000031223594,cquest,1,tourist_zone,41042071,relation/6439048,b'\x01\x01\x00\x00\x00\x9a\x9a:\xfbv\xe6\x02@\...,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00S\x00\x0...
3,Le Marais,multipolygon,2016-07-26T15:30:19Z,158826,JORFTEXT000031223582,cquest,2,tourist_zone,41040695,relation/6438571,"b""\x01\x01\x00\x00\x00;L\x88\xcb\x9d\xe5\x02@H...",b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\x90\x00...
4,Rennes - Saint-Sulpice,boundary,2016-07-26T17:30:29Z,158826,JORFTEXT000031223597,cquest,2,tourist_zone,41043224,relation/6439069,"b'\x01\x01\x00\x00\x00\x879y\x87""\xa0\x02@\x83...",b'\x01\x03\x00\x00\x00\x01\x00\x00\x00N\x00\x0...
5,Maillot-Ternes,boundary,2016-07-26T15:53:40Z,158826,JORFTEXT000031223588,cquest,2,tourist_zone,41041163,relation/6438646,b'\x01\x01\x00\x00\x00s\xc1\xa9\x06\xedN\x02@A...,b'\x01\x06\x00\x00\x00\x02\x00\x00\x00\x01\x03...
6,Saint-Germain,boundary,2016-07-26T17:30:29Z,158826,JORFTEXT000031223606,cquest,1,tourist_zone,41043224,relation/6439138,b'\x01\x01\x00\x00\x00\xb1ly\x7fl\xaa\x02@&6m\...,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00E\x00\x0...
7,Haussmann,multipolygon,2016-07-26T17:22:16Z,158826,JORFTEXT000031223579,cquest,2,tourist_zone,41043008,relation/6438520,b'\x01\x01\x00\x00\x00\x0b\xeb\xae\xe4\xfb\xa8...,"b""\x01\x03\x00\x00\x00\x01\x00\x00\x00i\x00\x0..."
8,Les Halles,boundary,2016-07-26T17:22:16Z,158826,JORFTEXT000031223585,cquest,2,tourist_zone,41043008,relation/6438629,b'\x01\x01\x00\x00\x00\x02\xfd\xf1=\x06\xca\x0...,"b""\x01\x03\x00\x00\x00\x01\x00\x00\x00B\x00\x0..."
9,Champs-Elysées Montaigne,boundary,2016-07-26T14:10:50Z,158826,JORFTEXT000031223576,cquest,1,tourist_zone,41039106,relation/6438476,b'\x01\x01\x00\x00\x00\xda\x0c\xd6\xa7Nr\x02@\...,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\x1e\x00...