# EDA Indicateur 4

In [1]:
import pandas as pd

df = pd.read_parquet(r"./raw/amenagements-cyclables.parquet")
df.head(10)

,osm_id,nom,amenagement,cote_amenagement,sens,surface,arrondissement,bois,coronapiste,amenagement_temporaire,infrastructure_bidirection,voie_a_sens_unique,position_amenagement,vitesse_maximale_autorisee,date_export,source,st_length_shape,geo_shape,geo_point_2d
0,693056491,Rue des Pyrénées,couloir bus ouvert aux vélos,droit,NaN,Asphalte,20,non,non,non,non,non,niveau chaussée,30 km/h,2022-01-01 02:00:00+01:00,OSMIUM,34.542167,b'\x01\x02\x00\x00\x00\x03\x00\x00\x00\xd4\xe6...,b'\x01\x01\x00\x00\x00?Q)\x8c8%\x03@EN:D|oH@'
1,693110778,NaN,piste cyclable,droit,NaN,Pavé lisse,14,non,non,non,non,oui,traversée de carrefo,non définie,2022-01-01 02:00:00+01:00,OSMIUM,36.847565,b'\x01\x02\x00\x00\x00\x08\x00\x00\x00Ft\xe7\x...,b'\x01\x01\x00\x00\x00]qQ\x1a)\x9b\x02@\xa9\x8...
2,694004567,Boulevard de Bercy,bande cyclable,droit,NaN,Asphalte,12,non,non,non,non,oui,niveau chaussée,30 km/h,2022-01-01 02:00:00+01:00,OSMIUM,16.532197,b'\x01\x02\x00\x00\x00\x03\x00\x00\x00\xfe\x19...,"b""\x01\x01\x00\x00\x00\xc3\x14;\xc2'\t\x03@\xb..."
3,694769031,Rue du Théâtre,piste cyclable,droit,NaN,NaN,15,non,non,non,oui,non,indéfini,non définie,2022-01-01 02:00:00+01:00,OSMIUM,6.406600,b'\x01\x02\x00\x00\x00\x03\x00\x00\x007\xc9\x1...,b'\x01\x01\x00\x00\x00@\x1f9\xba\xe9D\x02@\xed...
4,696354695,Avenue Daumesnil,piste cyclable,droit,NaN,Asphalte,12,non,non,non,non,non,indéfini,30 km/h,2022-01-01 02:00:00+01:00,OSMIUM,33.586907,b'\x01\x02\x00\x00\x00\x02\x00\x00\x00x{\xd7\x...,"b'\x01\x01\x00\x00\x00\xe1S\xd2]\xe4,\x03@\xaa..."
5,697939001,Place de la Bastille,couloir bus ouvert aux vélos,droit,NaN,Asphalte,12,non,non,non,non,oui,niveau chaussée,30 km/h,2022-01-01 02:00:00+01:00,OSMIUM,101.181334,b'\x01\x02\x00\x00\x00\n\x00\x00\x002a\x11\xe3...,b'\x01\x01\x00\x00\x00\t+5\xcf\xdb\xf4\x02@M5}...
6,698892814,Rue Charlemagne,voie piétonne,droit,NaN,Asphalte,4,non,non,non,non,oui,indéfini,non définie,2022-01-01 02:00:00+01:00,OSMIUM,68.610394,b'\x01\x02\x00\x00\x00\x07\x00\x00\x00\x7fX.(9...,b'\x01\x01\x00\x00\x00\xc4\xe5\x13\x89!\xe2\x0...
7,700088130,Route de la Ceinture du Lac Daumesnil,voie piétonne,droit,NaN,Béton,12,oui,non,non,oui,non,indéfini,non définie,2022-01-01 02:00:00+01:00,OSMIUM,12.334717,b'\x01\x02\x00\x00\x00\x02\x00\x00\x00\x85\xb4...,b'\x01\x01\x00\x00\x00\xc4\xbeT\xff\x1aE\x03@\...
8,701883670,Route des Tribunes,piste cyclable,droit,NaN,Asphalte,16,oui,non,non,non,oui,niveau chaussée,non définie,2022-01-01 02:00:00+01:00,OSMIUM,465.678029,b'\x01\x02\x00\x00\x00\x0b\x00\x00\x00\x96q\xf...,b'\x01\x01\x00\x00\x00\xb6Y\xdep\xd1\xd5\x01@%...
9,702192838,Route de la Pyramide,voie verte,droit,NaN,Asphalte,12,oui,non,non,oui,non,niveau trottoir,non définie,2022-01-01 02:00:00+01:00,OSMIUM,774.752392,b'\x01\x02\x00\x00\x00\n\x00\x00\x00+uA\xebX\x...,b'\x01\x01\x00\x00\x00A\x06s\xf2\x96\x87\x03@\...

In [2]:
import pandas as pd

df = pd.read_csv(r"./raw/emplacement-des-gares-idf.csv", sep=";")
df.head(10)

,Geo Point,Geo Shape,OBJECTID_1,gares_id,nom_long,nom_so_gar,nom_su_gar,id_ref_ZdC,nom_ZdC,id_ref_ZdA,...,termetro,tertram,terval,exploitant,idf,principal,x,y,picto ligne,nom_iv
0,"48.667901961049886, 2.5475480458143664","{""coordinates"": [2.547548045814366, 48.6679019...",91,196,Combs-la-Ville - Quincy,NaN,NaN,62558,Combs-la-Ville - Quincy,45771,...,0,0,0,SNCF,1,0,666681.8714,6.840955e+06,https://data.iledefrance-mobilites.fr/api/expl...,Combs-la-Ville - Quincy
1,"48.613427913594734, 2.4729336504587436","{""coordinates"": [2.472933650458744, 48.6134279...",94,207,Corbeil-Essonnes,NaN,NaN,60309,Corbeil-Essonnes,43115,...,0,0,0,SNCF,1,1,661146.9910,6.834933e+06,https://data.iledefrance-mobilites.fr/api/expl...,Corbeil-Essonnes
2,"48.843772576851464, 2.3739164698064985","{""coordinates"": [2.373916469806499, 48.8437725...",128,307,Gare de Lyon,NaN,NaN,73626,Gare de Lyon,470195,...,0,0,0,SNCF,1,1,654051.0804,6.860596e+06,https://data.iledefrance-mobilites.fr/api/expl...,Gare de Lyon
3,"49.03318276903128, 2.478033365115082","{""coordinates"": [2.478033365115082, 49.0331827...",190,452,Les Noues,NaN,NaN,66650,Les Noues,47968,...,0,0,0,SNCF,1,0,661831.4373,6.881603e+06,https://data.iledefrance-mobilites.fr/api/expl...,Les Noues
4,"49.13828637527201, 2.4901789854211955","{""coordinates"": [2.490178985421196, 49.1382863...",242,957,Orry-la-Ville-Coye-la-Forêt,NaN,NaN,411422,Orry-la-Ville - Coye,411421,...,0,0,0,SNCF,0,1,662795.0403,6.893287e+06,https://data.iledefrance-mobilites.fr/api/expl...,Orry-la-Ville-Coye-la-Forêt
5,"49.099586939193706, 2.525531713992054","{""coordinates"": [2.525531713992054, 49.0995869...",284,845,Survilliers-Fosses,NaN,NaN,69450,Survilliers - Fosses,47958,...,0,0,0,SNCF,1,0,665349.0638,6.888966e+06,https://data.iledefrance-mobilites.fr/api/expl...,Survilliers-Fosses
6,"48.99377714689272, 2.4161874889269837","{""coordinates"": [2.416187488926984, 48.9937771...",356,909,Villiers-le-Bel-Gonesse-Arnouville,NaN,NaN,66009,Villiers-le-Bel - Gonesse - Arnouville,43222,...,0,0,0,SNCF,1,0,657276.6642,6.877253e+06,https://data.iledefrance-mobilites.fr/api/expl...,Villiers-le-Bel-Gonesse-Arnouville
7,"48.531501986486845, 2.3705184977367075","{""coordinates"": [2.370518497736708, 48.5315019...",471,48,Ballancourt,NaN,NaN,59825,Ballancourt,43087,...,0,0,0,SNCF,1,0,653524.9404,6.825881e+06,https://data.iledefrance-mobilites.fr/api/expl...,Ballancourt
8,"49.136000564590994, 2.2426777767781676","{""coordinates"": [2.242677776778168, 49.1360005...",69,138,Champagne-sur-Oise,NaN,NaN,67241,Champagne-sur-Oise,47590,...,0,0,0,SNCF,1,0,644731.2902,6.893177e+06,https://data.iledefrance-mobilites.fr/api/expl...,Champagne-sur-Oise
9,"48.966326544842126, 2.3165820711557","{""coordinates"": [2.3165820711557, 48.966326544...",137,390,La Barre-Ormesson,NaN,NaN,65360,La Barre Ormesson,46470,...,0,0,0,SNCF,1,0,649961.2985,6.874258e+06,https://data.iledefrance-mobilites.fr/api/expl...,La Barre-Ormesson

In [3]:
import pandas as pd

df = pd.read_parquet(r"./raw/plan de voirie.parquet")
df.head(10)

,OBJECTID,NUM_PAVE,IGDS_LEVEL,LIB_LEVEL,LIB_CLASSE,geo_shape,geo_point_2d
0,201825,133G,21,TRANSPORT,NaN,"{""coordinates"": [[2.355696017000305, 48.820648...","48.820641707228745, 2.355690026743711"
1,201854,151G,21,TRANSPORT,NaN,"{""coordinates"": [[2.2925539116883042, 48.83081...","48.830817394205965, 2.292559511087538"
2,201894,193J,21,TRANSPORT,NaN,"{""coordinates"": [[2.405373885476651, 48.877921...","48.87792883476874, 2.4053770841905955"
3,201897,154C,21,TRANSPORT,NaN,"{""coordinates"": [[2.279349104077107, 48.835857...","48.835850671739536, 2.2793447032358625"
4,201903,173B,21,TRANSPORT,NaN,"{""coordinates"": [[2.3126839621584003, 48.89402...","48.89403165510765, 2.3126774919504967"
5,201904,173B,21,TRANSPORT,NaN,"{""coordinates"": [[2.305529956793193, 48.890853...","48.890847195879076, 2.3055367731804695"
6,201912,142C,21,TRANSPORT,NaN,"{""coordinates"": [[2.344144492067862, 48.819424...","48.81943176131715, 2.3441465527689136"
7,201922,184B,21,TRANSPORT,NaN,"{""coordinates"": [[2.3683335048294976, 48.89860...","48.89859769272887, 2.3683338948591546"
8,201929,184B,21,TRANSPORT,NaN,"{""coordinates"": [[2.366460169737078, 48.898538...","48.898530981301846, 2.36646052531536"
9,201944,163E,21,TRANSPORT,NaN,"{""coordinates"": [[2.274746085480351, 48.870281...","48.870285093954166, 2.274735703061824"

In [4]:
import pandas as pd

df = pd.read_parquet(r"./raw/velib-emplacement-des-stations.parquet")
df.head(10)

,stationcode,name,capacity,coordonnees_geo,station_opening_hours
0,10115,Granges aux Belles,27,b'\x01\x01\x00\x00\x00\xec\x97\x06I\xd6\xf1\x0...,NaN
1,12128,Pyramide - Ecole du Breuil,34,b'\x01\x01\x00\x00\x00\x01\x00\x00(d\xab\x03@\...,NaN
2,8028,Arsène Houssaye - Champs-Elysées,0,b'\x01\x01\x00\x00\x00\xc9\xff\xff\xf6\xdfa\x0...,NaN
3,16136,Théophile Gautier - François Millet,30,b'\x01\x01\x00\x00\x00\x01\x00\x00X*/\x02@\x83...,NaN
4,19022,Marché Secrétan,26,b'\x01\x01\x00\x00\x00\x00\x00\x00R\xda\xfc\x0...,NaN
5,21104,Madame de Sanzillon - Mozart,22,b'\x01\x01\x00\x00\x00\x01\x00\x00\xa8\xc7\x8c...,NaN
6,51004,Général Delambre - Prebuard,29,"b""\x01\x01\x00\x00\x0091\xb2\xef\x8e\xc9\x01@\...",NaN
7,12009,Charenton - Diderot,18,b'\x01\x01\x00\x00\x00\xb7\xff\xff\x02\xd2\x08...,NaN
8,19008,Flandre - Alphonse Karr,26,b'\x01\x01\x00\x00\x00\x86\x1c[\xcf\x10\x0e\x0...,NaN
9,12027,Montgallet - Charenton,16,b'\x01\x01\x00\x00\x00\x8b\x93>\xa3\xdd\x16\x0...,NaN