# EDA Indicateur 2

In [1]:
import pandas as pd

df = pd.read_parquet(r"./raw/ilots-de-fraicheur-espaces-verts-frais.parquet")
df.head(10)

,identifiant,nsq_espace_vert,nom,type,p_vegetation_h,proportion_vegetation_haute,adresse,arrondissement,statut_ouverture,ouvert_24h,...,horaires_vendredi,horaires_samedi,horaires_dimanche,categorie,proposition_usager,id_dicom,geo_shape,geo_point_2d,surf_veget_sup8m_2024,indice_veget_sup8m_2024
0,ID1598,12950.0,JARDINIERES DU BOULEVARD BOURDON,Décorations sur la voie publique,0.400000,40.000000,2 BOULEVARD BOURDON,75004,NaN,Oui,...,NaN,NaN,NaN,Jardiniere,NaN,NaN,b'\x01\x06\x00\x00\x00 \x00\x00\x00\x01\x03\x0...,b'\x01\x01\x00\x00\x00\xdf;\x1btA\xef\x02@f\xa...,624.205223,0.400000
1,ID827,NaN,Jardin de la place Mohamed Bouazizi,Promenades ouvertes,0.700000,70.000000,place Mohamed Bouazizi,75014,NaN,Oui,...,NaN,NaN,NaN,NaN,NaN,NaN,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\x0f\x00...,b'\x01\x01\x00\x00\x00\x7f\xbfX2f\xb3\x02@\xc5...,120.179045,0.700000
2,ID681,147.0,MAIL PIERRE DESPROGES DIT TROTTOIR PIERRE DESP...,Promenades ouvertes,0.685502,68.550155,143 RUE DE LA ROQUETTE,75011,NaN,Oui,...,NaN,NaN,NaN,Mail,NaN,NaN,b'\x01\x06\x00\x00\x00\x02\x00\x00\x00\x01\x03...,b'\x01\x01\x00\x00\x00q.\xe4D\xda\x14\x03@\xc6...,522.406493,0.408195
3,ID733,664.0,MAIL MARCEL ACHARD,Promenades ouvertes,0.382438,38.243819,6 PL MARCEL ACHARD,75019,NaN,Non,...,NaN,NaN,NaN,Mail,NaN,NaN,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00 \x00\x0...,b'\x01\x01\x00\x00\x00x\x19\xfeXs\x03\x03@\xe9...,1914.907047,0.444426
4,ID1211,10045.0,Bois de Boulogne,Bois,0.822828,82.282848,NaN,75016,NaN,Non,...,00h00 - 23h59,00h00 - 23h59,00h00 - 23h59,Bois,NaN,2779,b'\x01\x06\x00\x00\x00\t\x00\x00\x00\x01\x03\x...,b'\x01\x01\x00\x00\x00\x10\xab\xaf\xf8{%\x02@\...,153846.532000,0.630035
5,ID745,374.0,PROMENADE D'AUSTRALIE 15E,Promenades ouvertes,0.115169,11.516945,74 QUAI BRANLY,75015,NaN,Oui,...,NaN,NaN,NaN,Promenade,NaN,NaN,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\xc7\x00...,b'\x01\x01\x00\x00\x00L\xde)HQQ\x02@!\xc3\xdeY...,1750.368973,0.216565
6,ID843,827.0,SQUARE RESTIF DE LA BRETONNE,Promenades ouvertes,0.529956,52.995639,2 RUE BUCHERIE,75005,NaN,Non,...,NaN,NaN,NaN,Square,NaN,NaN,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\x14\x00...,b'\x01\x01\x00\x00\x00{\xaf\xfe\xe1R\xcb\x02@\...,29.161931,0.554146
7,ID910,11513.0,PARC DE LA VILLETTE,Jardins d'Etat,0.266145,26.614466,211 AVENUE JEAN JAURES,75019,NaN,Oui,...,00h00 - 23h59,00h00 - 23h59,00h00 - 23h59,NaN,NaN,1809,b'\x01\x06\x00\x00\x00\x04\x00\x00\x00\x01\x03...,b'\x01\x01\x00\x00\x00\x85\xd8\xa7\x04\x89\x1e...,89062.275450,0.334295
8,ID835,10045.0,La Garde Républicaine,Bois,0.313282,31.328162,93 w Avenue de l'Hippodrome,75016,NaN,Non,...,NaN,NaN,NaN,Bois,NaN,NaN,b'\x01\x06\x00\x00\x00\x01\x00\x00\x00\x01\x03...,b'\x01\x01\x00\x00\x00t\x9d\xde\xa0u\t\x02@?-\...,932.190193,0.304437
9,ID163,849.0,JARDINET DE LA PLACE RAOUL FOLLEREAU,Jardinets décoratifs,0.271363,27.136291,2 PLACE RAOUL FOLLEREAU,75010,NaN,Non,...,NaN,NaN,NaN,Jardinet,NaN,NaN,b'\x01\x06\x00\x00\x00\r\x00\x00\x00\x01\x03\x...,b'\x01\x01\x00\x00\x00\x82~\xf6\n\x10\xe9\x02@...,248.265551,0.254253

In [2]:
import pandas as pd

df = pd.read_parquet(r"./raw/les-arbres.parquet")
df.head(10)

,idbase,typeemplacement,domanialite,arrondissement,complementadresse,adresse,idemplacement,libellefrancais,genre,espece,varieteoucultivar,circonferenceencm,hauteurenm,stadedeveloppement,remarquable,geo_point_2d
0,126117,Arbre,Jardin,PARIS 20E ARRDT,NaN,JARDIN DE LA GARE DE CHARONNE / 59 BOULEVARD D...,000103036,Cèdre,Cedrus,atlantica,NaN,130,15,Adulte,NON,b'\x01\x01\x00\x00\x00\xc1\xc1\xb1d\xafF\x03@T...
1,141306,Arbre,CIMETIERE,PARIS 15E ARRDT,NaN,CIMETIERE DE VAUGIRARD / AVENUE PRINCIPALE / D...,A14000011002,Erable,Acer,platanoides,NaN,75,8,Adulte,NON,b'\x01\x01\x00\x00\x00P\x0f\xf1[\xb6F\x02@\xe5...
2,250335,Arbre,Alignement,PARIS 19E ARRDT,NaN,RUE MANIN,001002013,Platane,Platanus,x hispanica,NaN,120,20,Adulte,NON,b'\x01\x01\x00\x00\x00\x8e+\xa1)\x91\x1e\x03@\...
3,278516,Arbre,Alignement,PARIS 13E ARRDT,NaN,BOULEVARD KELLERMANN,000202013,Marronnier,Aesculus,x carnea,''Briotii'',115,10,Adulte,NON,b'\x01\x01\x00\x00\x00\xda3\xc2\xa1\xd1\xdc\x0...
4,216594,Arbre,Alignement,PARIS 19E ARRDT,15,AVENUE DE LAUMIERE,000101011,Paulownia,Paulownia,tomentosa,NaN,60,8,Jeune (arbre),NON,b'\x01\x01\x00\x00\x00\xcf\x0b\xb4\xac\xe7\x0b...
5,223855,Arbre,Alignement,PARIS 11E ARRDT,116,BOULEVARD RICHARD LENOIR,000704007,Platane,Platanus,x hispanica,NaN,30,6,Jeune (arbre),NON,b'\x01\x01\x00\x00\x00\xcb;\x10I`\xf7\x02@\xf2...
6,106474,Arbre,Jardin,PARIS 7E ARRDT,Canton 10,JARDIN DU CHAMP DE MARS ET PELOUSES DE L ECOLE...,A01002004,Platane,Platanus,x hispanica,NaN,95,12,Adulte,NON,b'\x01\x01\x00\x00\x00\x1a\x8c\xce\xdf\xd0f\x0...
7,266201,Arbre,Alignement,PARIS 15E ARRDT,111,BOULEVARD LEFEBVRE,000701006,Platane,Platanus,x hispanica,NaN,110,15,Adulte,NON,b'\x01\x01\x00\x00\x00\xf0\xecd\xf3y`\x02@\x04...
8,157556,Arbre,CIMETIERE,VAL-DE-MARNE,NaN,CIMETIERE DE THIAIS / AVENUE I / DIV 91,A12100091008,Frêne à fleurs,Fraxinus,ornus,NaN,20,5,NaN,NON,b'\x01\x01\x00\x00\x00\xa6v\xc7\x83\x1b\x00\x0...
9,105989,Arbre,Jardin,PARIS 20E ARRDT,NaN,SQUARE SEVERINE / 1 RUE LE VAU,000202022,Sequoia,Sequoiadendron,giganteum,NaN,215,15,Adulte,NON,b'\x01\x01\x00\x00\x00\xa7\x86t\xf5\xceE\x03@\...

In [3]:
import pandas as pd

df = pd.read_parquet(r"./raw/lieux-de-tournage-a-paris.parquet")
df.head(10)

,id_lieu,annee_tournage,type_tournage,nom_tournage,nom_realisateur,nom_producteur,adresse_lieu,ardt_lieu,date_debut,date_fin,coord_x,coord_y,geo_shape,geo_point_2d
0,2016-1939,2016-01-01,Série TV,LES HOMMES DE L'OMBRE,FRED GARSON,MACONDO,AVENUE DU PRESIDENT WILSON,75016,2016-02-13,2016-02-13,2.294570,48.864614,b'\x01\x01\x00\x00\x00c#+\x84G[\x02@\xa2k\xeb\...,b'\x01\x01\x00\x00\x00c#+\x84G[\x02@\xa2k\xeb\...
1,2016-1495,2016-01-01,Long métrage,MAMAN A TORT,MARC FITOUSSI,AVENUE B,PLACE D'ITALIE,75013,2016-01-06,2016-01-06,2.355564,48.832294,b'\x01\x01\x00\x00\x00\xf3N3\xf01\xd8\x02@\xe3...,b'\x01\x01\x00\x00\x00\xf3N3\xf01\xd8\x02@\xe3...
2,2020-1082,2020-01-01,Long métrage,STELLA EST AMOUREUSE,Sylvie Verheyde,ATELIER DE PRODUCTION,"rue buot, 75013 paris",75013,2020-12-22,2020-12-22,2.350066,48.826579,b'\x01\x01\x00\x00\x00%\x81\xa8-\xef\xcc\x02@K...,b'\x01\x01\x00\x00\x00%\x81\xa8-\xef\xcc\x02@K...
3,2016-2623,2016-01-01,Long métrage,THE ESCAPE,DOMINIC SAVAGE,HANNA FILMS,BOULEVARD DE DENAIN,75010,2016-10-19,2016-10-19,2.354527,48.879391,"b""\x01\x01\x00\x00\x00'u\x80@\x12\xd6\x02@}#a\...","b""\x01\x01\x00\x00\x00'u\x80@\x12\xd6\x02@}#a\..."
4,2019-878,2019-01-01,Long métrage,PARENT D'ELEVE,NOEMIE SAGLIO,RECTANGLE PRODUCTIONS,"15 rue jacques hillairet, 75012 paris",75012,2019-07-16,2019-07-16,2.387530,48.842767,b'\x01\x01\x00\x00\x00\x91!U\x89\xa9\x19\x03@\...,b'\x01\x01\x00\x00\x00\x91!U\x89\xa9\x19\x03@\...
5,2019-956,2019-01-01,Série TV,FIND ME IN PARIS Saison 3( LENA REVE D'ETOILES),"Matt BLOOM, Robert BURKE, Ronan BURKE",Cottonwood media,"avenue hussein 1er de jordanie, 75116 paris",75116,2019-08-28,2019-08-28,2.289066,48.861750,b'\x01\x01\x00\x00\x00\x82\xbc\xcc\x06\x02P\x0...,b'\x01\x01\x00\x00\x00\x82\xbc\xcc\x06\x02P\x0...
6,2021-1742,2021-01-01,Série TV,SOUS CONTROLE,ERWAN LE DUC,EX NIHILO,"place de la fontaine timbaud, 75011 paris",75011,2021-12-07,2021-12-07,2.371343,48.866165,b'\x01\x01\x00\x00\x00\xb3\x8c\x81\xdd\x82\xf8...,b'\x01\x01\x00\x00\x00\xb3\x8c\x81\xdd\x82\xf8...
7,2017-549,2017-01-01,Série TV,Baron noir,Antoine Chevrollier - Ziad Doueiri,KWAI,"rue victor cousin, 75005 paris",75005,2017-09-28,2017-09-28,2.342695,48.848261,b'\x01\x01\x00\x00\x00\x80\x17&\xe9\xd6\xbd\x0...,b'\x01\x01\x00\x00\x00\x80\x17&\xe9\xd6\xbd\x0...
8,2017-1618,2017-01-01,Long métrage,BUDAPEST,Xavier Gens,LABYRINTHE FILMS,"rue la condamine, 75017 paris",75017,2017-07-28,2017-07-29,2.321646,48.885757,b'\x01\x01\x00\x00\x003\xcaE\x15\xbb\x92\x02@\...,b'\x01\x01\x00\x00\x003\xcaE\x15\xbb\x92\x02@\...
9,2017-595,2017-01-01,Série TV,FIND ME IN PARIS 3,MATT BLOOM et RANDALL THORN,COTTONWOOD MEDIA,"quai de la tournelle, 75005 paris",75005,2017-09-29,2017-09-29,2.352592,48.850699,"b""\x01\x01\x00\x00\x004'n\x94\x1b\xd2\x02@\x18...","b""\x01\x01\x00\x00\x004'n\x94\x1b\xd2\x02@\x18..."

In [4]:
import pandas as pd

df = pd.read_parquet(r"./raw/liste_des_associations_parisiennes.parquet")
df.head(10)

,pr_nom_statutaire,cp_adresse_code_postal,cp_adresse_ville,sa_secteur_d_activit_1,sa_secteur_d_activit_2,sa_secteur_d_activit_3,sa_libell_domaine_d_activit,sa_libell_secteur_d_activit,pv_public_vis,sg_secteur_gographique,cl_id_partenaire
0,YOGA ET CETERA,75018.0,PARIS,Sport,Culture & Arts,Sant,Culture & Education,Culture & Arts,Adultes,National,1350.0
1,CHOEUR · PRENDRE,75015.0,PARIS,Loisirs,Culture & Arts,NaN,Culture & Education,Culture & Arts,Femmes,Paris 15,29455.0
2,COMPAGNIE VARSORIO,75019.0,PARIS,Culture & Arts,Education & formation,Vie et animation locale,Vie Locale et Citoyenne,Vie et animation locale,Professionnels,International,1866.0
3,COMITE REGIONAL DE L'ACADEMIE DE PARIS DE LA F...,75014.0,PARIS,Sport,Loisirs,Education & formation,Sports Loisirs,Sport,Tous,Ile de France,435.0
4,ERSR (ECOLE DE LA RESPIRATION SANDRA-ROMOND),75020.0,PARIS,Sport,Education & formation,Sant,Sports Loisirs,Sport,Tous,Paris 7,9323.0
5,PARI MULTI-GLISSE,75012.0,PARIS,Sport,Culture & Arts,Education & formation,Sports Loisirs,Sport,Personnes handicapes,Paris 4,6762.0
6,JUDO FRANCE PARIS,75019.0,PARIS,Sport,Loisirs,Social,Sports Loisirs,Sport,Personnes en difficults,Paris 5,829.0
7,COMPAGNIE VARSORIO,75019.0,PARIS,Culture & Arts,Education & formation,Vie et animation locale,Culture & Education,Education & formation,Seniors,Paris 16,1866.0
8,ECOLE PARISIENNE DE KARATE,75009.0,PARIS,Sport,Loisirs,NaN,Sports Loisirs,Loisirs,Jeunes enfants,Paris 9,5081.0
9,COMIT DPARTEMENTAL DE SPLOLOGIE DE PARIS,75014.0,PARIS,Sport,Education & formation,Environnement & cologie,Sports Loisirs,Sport,Associations,International,979.0

In [5]:
import pandas as pd

df = pd.read_parquet(r"./raw/plan de voirie.parquet")
df.head(10)

,OBJECTID,NUM_PAVE,IGDS_LEVEL,LIB_LEVEL,LIB_CLASSE,geo_shape,geo_point_2d
0,201825,133G,21,TRANSPORT,NaN,"{""coordinates"": [[2.355696017000305, 48.820648...","48.820641707228745, 2.355690026743711"
1,201854,151G,21,TRANSPORT,NaN,"{""coordinates"": [[2.2925539116883042, 48.83081...","48.830817394205965, 2.292559511087538"
2,201894,193J,21,TRANSPORT,NaN,"{""coordinates"": [[2.405373885476651, 48.877921...","48.87792883476874, 2.4053770841905955"
3,201897,154C,21,TRANSPORT,NaN,"{""coordinates"": [[2.279349104077107, 48.835857...","48.835850671739536, 2.2793447032358625"
4,201903,173B,21,TRANSPORT,NaN,"{""coordinates"": [[2.3126839621584003, 48.89402...","48.89403165510765, 2.3126774919504967"
5,201904,173B,21,TRANSPORT,NaN,"{""coordinates"": [[2.305529956793193, 48.890853...","48.890847195879076, 2.3055367731804695"
6,201912,142C,21,TRANSPORT,NaN,"{""coordinates"": [[2.344144492067862, 48.819424...","48.81943176131715, 2.3441465527689136"
7,201922,184B,21,TRANSPORT,NaN,"{""coordinates"": [[2.3683335048294976, 48.89860...","48.89859769272887, 2.3683338948591546"
8,201929,184B,21,TRANSPORT,NaN,"{""coordinates"": [[2.366460169737078, 48.898538...","48.898530981301846, 2.36646052531536"
9,201944,163E,21,TRANSPORT,NaN,"{""coordinates"": [[2.274746085480351, 48.870281...","48.870285093954166, 2.274735703061824"

In [6]:
import pandas as pd

df = pd.read_parquet(r"./raw/que-faire-a-paris.parquet")
df.head(10)

,id,event_id,url,title,lead_text,description,date_start,date_end,occurrences,date_description,...,contact_youtube,contact_bandcamp,contact_linkedin,contact_snapchat,contact_whatsapp,contact_instagram,contact_messenger,contact_pinterest,contact_soundcloud,univers
0,11022,4287,https://www.paris.fr/evenements/les-balades-gu...,Les balades guidées virtuelles d'Explore Paris,"Se balader dans les rues de Paris, y voir les ...",<p>Plus de 50 balades ou conférences virtuelle...,NaT,NaT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,15396,8604,https://www.paris.fr/evenements/paroles-d-adul...,"Paroles d’adultes, regards d’enfants : aborder...",Comment parler de la crise climatique avec nos...,<p><br><br><strong>POUR LES ENFANTS : </strong...,NaT,NaT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,53785,39683,https://www.paris.fr/evenements/montmartre-enc...,Montmartre Enchanté insolite : la visite chant...,Et si vous vous laissiez guider par la voix a ...,<p>La visite chantée et commentée de Montmartr...,2024-02-09 16:30:00+01:00,2026-09-27 18:30:00+02:00,2024-02-09T15:30:00+02:00_2024-02-09T17:00:00+...,Du vendredi 09 février 2024 au dimanche 27 sep...,...,NaN,NaN,NaN,NaN,NaN,https://www.instagram.com/la_veronica_antonelli,NaN,NaN,NaN,NaN
3,11018,4283,https://www.paris.fr/evenements/la-folle-et-in...,"La folle et inconvenante histoire des femmes, ...","Une immersion drôle, détonante et décalée dans...",<p>Ce spectacle met en scène une jeune femme q...,2023-10-24 00:00:00+02:00,2026-08-07 01:15:00+02:00,2026-08-06T21:00:00+02:00_2026-08-06T22:15:00+...,Le jeudi 06 août 2026<br />de 21h00 à 22h15<br />,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,66412,51122,https://www.paris.fr/evenements/jazzdedemain-l...,#JazzDeDemain LAURIANE LUDOSKY & EXCENTRIQUE,Reconnue pour sa voix envoûtante et sa présenc...,<p>Nouvelle résidence #JDD pleine de promesses...,2024-11-06 22:00:00+01:00,2026-07-17 01:10:00+02:00,2026-07-16T21:00:00+02:00_2026-07-16T22:10:00+...,Le jeudi 16 juillet 2026<br />de 21h00 à 22h10...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,66789,51437,https://www.paris.fr/evenements/paris-street-a...,Paris Street Art à la Butte-aux-Cailles,Et si l’histoire de la Butte-aux-Cailles se li...,<p>Découvrez les secrets d’un des quartiers le...,2024-10-01 02:00:00+02:00,2029-01-01 00:59:59+01:00,NaN,Du mardi 01 octobre 2024 au dimanche 31 décemb...,...,https://www.youtube.com/user/Cultival,NaN,https://www.linkedin.com/company/cultival/,NaN,NaN,https://www.instagram.com/cultivalparis/?hl=en,NaN,NaN,NaN,NaN
6,66827,51475,https://www.paris.fr/evenements/le-cambrioleur...,Le Cambrioleur de la Butte Montmartre,"Jeu de piste original et éducatif, découvrez M...","<p>Dans ce jeu de piste, improvisez-vous détec...",2024-10-01 02:00:00+02:00,2029-01-01 00:59:59+01:00,NaN,Du mardi 01 octobre 2024 au dimanche 31 décemb...,...,https://www.youtube.com/user/Cultival,NaN,https://www.linkedin.com/company/cultival/,NaN,NaN,https://www.instagram.com/cultivalparis/?hl=en,NaN,NaN,NaN,NaN
7,87381,67216,https://www.paris.fr/evenements/l-echo-des-sai...,L'écho des saisons,La programmation jeune public du Châtelet !,<p><em>L’Écho</em> <em>des</em> <em>saisons</e...,2026-06-07 02:00:00+02:00,2026-06-08 01:59:59+02:00,2026-06-07T00:00:00+02:00_2026-06-07T23:59:00+...,Le dimanche 07 juin 2026<br />de à <br />,...,NaN,NaN,NaN,NaN,NaN,https://www.instagram.com/theatrechatelet/,NaN,NaN,NaN,NaN
8,90308,69512,https://www.paris.fr/evenements/paris-sport-pr...,Paris sport proximité : Sport santé jeunesse a...,Participez à un large choix de disciplines pro...,<p>Venez pratiquer une activité sportive proch...,2025-09-22 02:00:00+02:00,2026-07-05 01:59:59+02:00,NaN,Du lundi 22 septembre 2025 au samedi 04 juille...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,48826,34970,https://www.paris.fr/evenements/paris-sport-pr...,Paris sport proximité : Badminton et Volley-ba...,Participez à un large choix de disciplines pro...,<p>Venez pratiquer une activité sportive proch...,2025-09-22 02:00:00+02:00,2026-07-05 01:59:59+02:00,NaN,Du lundi 22 septembre 2025 au samedi 04 juille...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
import pandas as pd

df = pd.read_parquet(r"./raw/zones-touristiques-internationales.parquet")
df.head(10)

,name,type,_timestamp,_uid,source,_user,_version,boundary,_changeset,_id,geo_point_2d,geo_shape
0,Saint-Honoré - Vendôme,boundary,2016-07-26T17:22:16Z,158826,JORFTEXT000031223603,cquest,1,tourist_zone,41043008,relation/6439132,b'\x01\x01\x00\x00\x00JM\x0c\x0c\x80\xa7\x02@\...,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00d\x00\x0...
1,Montmartre,boundary,2016-07-26T16:15:57Z,158826,JORFTEXT000031223591,cquest,1,tourist_zone,41041604,relation/6438767,b'\x01\x01\x00\x00\x00\xec\xf38C\x97\xb5\x02@\...,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00H\x00\x0...
2,Olympiades,boundary,2016-07-26T16:39:02Z,158826,JORFTEXT000031223594,cquest,1,tourist_zone,41042071,relation/6439048,b'\x01\x01\x00\x00\x00\x9a\x9a:\xfbv\xe6\x02@\...,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00S\x00\x0...
3,Le Marais,multipolygon,2016-07-26T15:30:19Z,158826,JORFTEXT000031223582,cquest,2,tourist_zone,41040695,relation/6438571,"b""\x01\x01\x00\x00\x00;L\x88\xcb\x9d\xe5\x02@H...",b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\x90\x00...
4,Rennes - Saint-Sulpice,boundary,2016-07-26T17:30:29Z,158826,JORFTEXT000031223597,cquest,2,tourist_zone,41043224,relation/6439069,"b'\x01\x01\x00\x00\x00\x879y\x87""\xa0\x02@\x83...",b'\x01\x03\x00\x00\x00\x01\x00\x00\x00N\x00\x0...
5,Maillot-Ternes,boundary,2016-07-26T15:53:40Z,158826,JORFTEXT000031223588,cquest,2,tourist_zone,41041163,relation/6438646,b'\x01\x01\x00\x00\x00s\xc1\xa9\x06\xedN\x02@A...,b'\x01\x06\x00\x00\x00\x02\x00\x00\x00\x01\x03...
6,Saint-Germain,boundary,2016-07-26T17:30:29Z,158826,JORFTEXT000031223606,cquest,1,tourist_zone,41043224,relation/6439138,b'\x01\x01\x00\x00\x00\xb1ly\x7fl\xaa\x02@&6m\...,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00E\x00\x0...
7,Haussmann,multipolygon,2016-07-26T17:22:16Z,158826,JORFTEXT000031223579,cquest,2,tourist_zone,41043008,relation/6438520,b'\x01\x01\x00\x00\x00\x0b\xeb\xae\xe4\xfb\xa8...,"b""\x01\x03\x00\x00\x00\x01\x00\x00\x00i\x00\x0..."
8,Les Halles,boundary,2016-07-26T17:22:16Z,158826,JORFTEXT000031223585,cquest,2,tourist_zone,41043008,relation/6438629,b'\x01\x01\x00\x00\x00\x02\xfd\xf1=\x06\xca\x0...,"b""\x01\x03\x00\x00\x00\x01\x00\x00\x00B\x00\x0..."
9,Champs-Elysées Montaigne,boundary,2016-07-26T14:10:50Z,158826,JORFTEXT000031223576,cquest,1,tourist_zone,41039106,relation/6438476,b'\x01\x01\x00\x00\x00\xda\x0c\xd6\xa7Nr\x02@\...,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\x1e\x00...