# EDA Indicateur 3

In [1]:
import pandas as pd

df = pd.read_csv(r"./raw/carte-des-points-daccueil-police-a-paris.csv", sep=";")
df.head(10)

,ardt,service,adresse,téléphone,horaires,accessibilité,WGS84
0,12e,DPGP Gare de Lyon,"80, allée de Bercy Voie N",01 53 02 94 00,tous les jours de 6 h30 à 22h40,Ce point d'accueil dispose d'aménagements spéc...,"48.840578, 2.381345"
1,7e,Commissariat central,"9, rue Fabert",01 44 18 69 07,7j/7 24h/24,Ce point d'accueil dispose d'aménagements spéc...,"48.8618757, 2.3116095"
2,16e,Commissariat central,62 avenue Mozart,01 55 74 50 00,7j/7 24h/24,Ce point d'accueil dispose d'aménagements spéc...,"48.8541871, 2.2690746"
3,19e,BDEP Amérique,"12, rue Augustin Thierry",01 56 41 30 00,du lundi au vendredi 9h - 20h,Ce point d'accueil ne dispose pas encore d'amé...,"48.8762512, 2.39369"
4,3e,Commissariat central,"4 bis, 6 rue aux Ours",01 42 76 13 00,7j/7 24h/24,Ce point d'accueil dispose d'aménagements spéc...,"48.8632377, 2.3516301"
5,6e,SAIP,"12, rue Jean Bart",01 44 39 71 70,7j/7 24h/24,Ce point d'accueil ne dispose pas encore d'amé...,"48.8473738, 2.3308785"
6,1er,BDEP - Vendôme,"45, place du Marché-Saint-Honoré",01 47 03 60 10,du lundi au vendredi 9h - 20h,Ce point d'accueil dispose d'aménagements spéc...,"48.8669683, 2.3314598"
7,16e,SAIP,"75, rue de la Faisanderie",01 40 72 22 50,sur rdv uniquement,Ce point d'accueil dispose d'aménagements spéc...,"48.8676036, 2.2751679"
8,16e,BDEP Auteuil,"74, rue Chardon Lagache",01 53 92 51 00,du lundi au vendredi 9h - 20h,Ce point d'accueil dispose d'aménagements spéc...,"48.8417002, 2.2638485"
9,12e,Commissariat central et SAIP,"80, avenue Daumesnil",01 44 87 50 12,7j/7 24h/24,Ce point d'accueil dispose d'aménagements spéc...,"48.8442726, 2.3815423"

In [2]:
import pandas as pd

df = pd.read_parquet(r"./raw/etablissements-scolaires-ecoles-elementaires.parquet")
df.head(10)

,id_projet,libelle,adresse,arr_libelle,arr_insee,annee_scol,type_etabl,geo_shape,geo_point_2d
0,ELEMENTAIRES (année scolaire 2022/2023),LITTRE (6) ELEM,6 RUE LITTRE,6ème Ardt,75106,2022-2023,Elémentaire,b'\x01\x01\x00\x00\x00\x9e\xd5`Z\x16\x97\x02@6...,b'\x01\x01\x00\x00\x00\x9e\xd5`Z\x16\x97\x02@6...
1,ELEMENTAIRES (année scolaire 2022/2023),CHAMPAGNE (17) POLY,17 CITE CHAMPAGNE,20ème Ardt,75120,2022-2023,Polyvalent,b'\x01\x01\x00\x00\x00%\x18\x0e\xeb\xd1;\x03@\...,b'\x01\x01\x00\x00\x00%\x18\x0e\xeb\xd1;\x03@\...
2,ELEMENTAIRES (année scolaire 2021/2022),ALAIN-FOURNIER ( 5) ELEM,5 SQUARE ALAIN-FOURNIER,14ème Ardt,75114,2021-2022,Elémentaire,b'\x01\x01\x00\x00\x00\x9c\xbb\xb5F\x1ev\x02@\...,b'\x01\x01\x00\x00\x00\x9c\xbb\xb5F\x1ev\x02@\...
3,ELEMENTAIRES (année scolaire 2021/2022),PIERRE FONCIN (8) ELEM A,8 RUE PIERRE FONCIN,20ème Ardt,75120,2021-2022,Elémentaire,b'\x01\x01\x00\x00\x00\xd4\xbdj\x9a\x15G\x03@\...,b'\x01\x01\x00\x00\x00\xd4\xbdj\x9a\x15G\x03@\...
4,ELEMENTAIRES (année scolaire 2021/2022),CHARENTON (315) ELEM,315 RUE DE CHARENTON,12ème Ardt,75112,2021-2022,Elémentaire,b'\x01\x01\x00\x00\x00\xe4\xebg\xd1I)\x03@CWRo...,b'\x01\x01\x00\x00\x00\xe4\xebg\xd1I)\x03@CWRo...
5,ELEMENTAIRES (année scolaire 2021/2022),ARAGO (30) ELEM,30 BOULEVARD ARAGO,13ème Ardt,75113,2021-2022,Elémentaire,b'\x01\x01\x00\x00\x00h+\xf7T\x98\xc7\x02@\xe9...,b'\x01\x01\x00\x00\x00h+\xf7T\x98\xc7\x02@\xe9...
6,ELEMENTAIRES (année scolaire 2021/2022),ORAN (18) ELEM,18 RUE D'ORAN,18ème Ardt,75118,2021-2022,Elémentaire,b'\x01\x01\x00\x00\x00Wy\xbc\xfa\x00\xd3\x02@\...,b'\x01\x01\x00\x00\x00Wy\xbc\xfa\x00\xd3\x02@\...
7,ELEMENTAIRES (année scolaire 2021/2022),MICHEL ANGE (51) ELEM,51 RUE MICHEL ANGE,16ème Ardt,75116,2021-2022,Elémentaire,b'\x01\x01\x00\x00\x00\xba\xa4l\xff\xab\x16\x0...,b'\x01\x01\x00\x00\x00\xba\xa4l\xff\xab\x16\x0...
8,ELEMENTAIRES (année scolaire 2022/2023),ETIENNE DOLET (31) ELEM,31 RUE ETIENNE DOLET,20ème Ardt,75120,2022-2023,Elémentaire,b'\x01\x01\x00\x00\x00\xef\x91+R9\x15\x03@7{\x...,b'\x01\x01\x00\x00\x00\xef\x91+R9\x15\x03@7{\x...
9,ELEMENTAIRES (année scolaire 2021/2022),PYRENEES (97) ELEM,97 RUE DES PYRENEES,20ème Ardt,75120,2021-2022,Elémentaire,b'\x01\x01\x00\x00\x00i\xbfy\x14\xf7=\x03@\x1f...,b'\x01\x01\x00\x00\x00i\xbfy\x14\xf7=\x03@\x1f...

In [3]:
import pandas as pd

df = pd.read_parquet(r"./raw/hopitaux.parquet")
df.head(10)

,finess_et,finess_ej,raison_sociale,raison_sociale_entite_juridique,adresse_administrative_1,adresse_administrative_2,num_voie,cpt_num,type_voie,voie,...,num_siret,code_ape,code_tarif,lib_tarification,code_psph,participant_service_public_hospitalier,date_ouverture,lat,lng,wgs84
0,950032722,950110080,HOPITAL DE JOUR FRANCOIS VILLON,HOPITAL DE JOUR FRANCOIS VILLON,NaN,NaN,10,NaN,R,DE L'ECLIPSE,...,NaN,NaN,3,ARS établissements Publics de santé dotation g...,1,Etablissement public de santé,2000-12-20,49.051263,2.030469,"49.0512627,2.0304689"
1,780000345,780110078,CH DE VERSAILLES-HOPITAL RICHAUD,CENTRE HOSPITALIER DE VERSAILLES-HOPITAL RICHAUD,NaN,NaN,1,NaN,R,RICHAUD,...,26780271800010,8610Z,3,ARS établissements Publics de santé dotation g...,1,Etablissement public de santé,1901-01-01,48.807402,2.133758,"48.8074016,2.1337584"
2,920025152,920804465,"CMP 92I05 ENFANTS ""CHAVISÈVRES""",NaN,NaN,NaN,259,NaN,AV,ROGER SALENGRO,...,26920141400225,8610Z,3,ARS établissements Publics de santé dotation g...,1,Etablissement public de santé,1991-01-01,48.817429,2.196222,"48.8174288,2.1962218"
3,920690278,920718202,"HOPITAL DE JOUR ""LES LIERRES""",NaN,NaN,NaN,12,NaN,R,ERNEST RENAN,...,78545228500014,NaN,15,ARS privé hors PSPH sous dotation globale,7,"Etab de santé privé non lucratif, non déclar i...",1977-01-01,48.820483,2.214372,"48.820483,2.2143718"
4,920810603,950140012,CMP ADULTES 92G02 (RABELAIS),CENTRE MEDICO-PSYCHOLOGIQUE POUR ADULTES,NaN,NaN,5,NaN,R,RABELAIS,...,26950008800191,NaN,3,ARS établissements Publics de santé dotation g...,1,Etablissement public de santé,1986-01-01,48.913200,2.290678,"48.9131996,2.2906781"
5,920814027,940140049,POLYCLINIQUE COUTURIER 92G18,HOPITAL DE JOUR ET CENTRE D'ACCUEIL D'URGENCE ...,NaN,POLICLINIQUE 18,42,NaN,R,P.VAILLANT COUTURIER,...,26940106300327,8610Z,3,ARS établissements Publics de santé dotation g...,1,Etablissement public de santé,1904-04-04,48.813071,2.296878,"48.8130707,2.2968778"
6,910002286,910140029,APPARTEMENT THERAPEUTIQUE,APPARTEMENT THERAPEUTIQUE,NaN,NaN,16,NaN,R,DES MOUSSERONS,...,NaN,NaN,3,ARS établissements Publics de santé dotation g...,1,Etablissement public de santé,1998-02-04,48.689932,2.301581,"48.6899321,2.3015811"
7,750000507,750040628,CENTRE PARIS SUD,CENTRE DE REEDUCATION FONCTIONNELLE PARIS SUD ...,NaN,CENTRE PARIS SUD,167,NaN,R,RAYMOND LOSSERAND,...,49197461400050,8610Z,4,ARS établissements PSPH dotation globale,6,Etablissement de santé privé d’intérêt collectif,1951-04-27,48.830368,2.311249,"48.8303682,2.3112489"
8,750007619,750720674,HOP DE JOUR CEREP (U.S.I.S. ET E.P.I.),HOPITAL DE JOUR CEREP (USIS ET EPI),ET PSYCHOTHÉRAPEUTIQUE,NaN,3,NaN,R,RIDDER,...,NaN,8610Z,15,ARS privé hors PSPH sous dotation globale,7,"Etab de santé privé non lucratif, non déclar i...",1981-04-21,48.831126,2.311870,"48.8311258,2.3118698"
9,750802761,910140011,CMP ADULTES SALNEUVE,CENTRE MEDICO-PSYCHOLOGIQUE PERRAY VAUCLUSE 75...,NaN,PV 75 G 20,18,NaN,R,SALNEUVE,...,26910206700163,NaN,3,ARS établissements Publics de santé dotation g...,1,Etablissement public de santé,1904-04-04,48.885550,2.314389,"48.8855503,2.3143885"

In [4]:
import pandas as pd

df = pd.read_parquet(r"./raw/les_bureaux_de_poste_et_agences_postales_en_idf.parquet")
df.head(10)

,libelle_du_site,caracteristique_du_site,adresse,complement_d_adresse,lieu_dit,code_postal,localite,pays,latitude,longitude,...,identifiant_a,reverse_geoloc_commune_nom_com,reverse_geoloc_commune_insee_com,reverse_geoloc_epci_nom_epci,reverse_geoloc_epci_code_epci,reverse_geoloc_departement_nom_dep,reverse_geoloc_departement_insee_dep,reverse_geoloc_region_nom_reg,reverse_geoloc_region_insee_reg,geo
0,FRANCONVILLE GUYON APC AP,Agence postale communale,CENTRE COMMERCIAL AVENUE DES MARAIS,AGENCE POSTALE COMMUNALE,EPINE GUYON,95130,FRANCONVILLE LA GARENNE,FRANCE,48.996073998,2.2209386035,...,12826D,Franconville,95252,CA Val Parisis,200058485,Val-d'Oise,95,Île-de-France,11,b'\x01\x01\x00\x00\x00\xbb\xa6cu{\xc4\x01@*\xe...
1,CERGY SME LPR RP,Relais poste,12 PLACE DES TOULEUSES,TABAC LES TOULEUSES CC LES TOULEUSES,NaN,95000,CERGY,FRANCE,49.030038746,2.0829225668,...,13101D,Cergy,95127,CA de Cergy-Pontoise,249500109,Val-d'Oise,95,Île-de-France,11,b'\x01\x01\x00\x00\x00\x0f\r\x84N\xd3\xa9\x00@...
2,SARCELLES SABLONS AP,Agence postale communale,14 RUE RAOUL DUFY,NaN,NaN,95200,SARCELLES,FRANCE,48.9723,2.3808,...,15799D,Sarcelles,95585,CA Roissy Pays de France,200055655,Val-d'Oise,95,Île-de-France,11,b'\x01\x01\x00\x00\x00\xce\x88\xd2\xde\xe0\x0b...
3,PERSAN BEAUMONT SNCF RELAY,Point partenaire,PLACE DE LA GARE,VESTIBULE,NaN,95340,PERSAN,FRANCE,49.1479,2.2792,...,17167D,Persan,95487,CC du Haut Val d'Oise,249500489,Val-d'Oise,95,Île-de-France,11,b'\x01\x01\x00\x00\x00yX\xa85\xcd;\x02@\t\x8a\...
4,ANDILLY BP,Bureau de Poste,1 PLACE LOUIS JEAN FINOT,NaN,NaN,95580,ANDILLY,FRANCE,49.004917,2.299529,...,17411A,Andilly,95014,CA Plaine Vallée,200056380,Val-d'Oise,95,Île-de-France,11,b'\x01\x01\x00\x00\x00\xf1\xa0\xd9uoe\x02@\xe3...
5,AUVERS SUR OISE BP,Bureau de Poste,4 PLACE DE LA MAIRIE,NaN,NaN,95430,AUVERS SUR OISE,FRANCE,49.070132,2.172213,...,17420A,Auvers-sur-Oise,95039,CC Sausseron Impressionnistes,249500430,Val-d'Oise,95,Île-de-France,11,b'\x01\x01\x00\x00\x00\x82\x91\x975\xb1`\x01@\...
6,GOUSSAINVILLE,Bureau de Poste,23 RUE DE LA REPUBLIQUE,NaN,NaN,95190,GOUSSAINVILLE,FRANCE,49.033993,2.47024,...,17460A,Goussainville,95280,CA Roissy Pays de France,200055655,Val-d'Oise,95,Île-de-France,11,b'\x01\x01\x00\x00\x00\x17+j0\r\xc3\x03@\x7f\x...
7,MARINES LE VEXIN BP,Bureau de Poste,10 PLACE DE VERDUN,NaN,NaN,95640,MARINES,FRANCE,49.145255,1.980181,...,17469A,Marines,95370,CC Vexin Centre,200035970,Val-d'Oise,95,Île-de-France,11,b'\x01\x01\x00\x00\x00\xb8\x91\xb2E\xd2\xae\xf...
8,MONTLIGNON BP,Bureau de Poste,12 RUE DE PARIS,NaN,NaN,95680,MONTLIGNON,FRANCE,49.008957,2.284791,...,17477A,Montlignon,95426,CA Plaine Vallée,200056380,Val-d'Oise,95,Île-de-France,11,b'\x01\x01\x00\x00\x00\xa3\x8f\xf9\x80@G\x02@\...
9,PRESLES BP,Bureau de Poste,54 RUE DU FOUR DU GUE,NaN,NaN,95590,PRESLES,FRANCE,49.11263,2.287249,...,17488A,Presles,95504,CC de la Vallée de l'Oise et des Trois Forêts,249500455,Val-d'Oise,95,Île-de-France,11,b'\x01\x01\x00\x00\x00:x&4IL\x02@5F\xeb\xa8j\x...

In [5]:
import pandas as pd

df = pd.read_parquet(r"./raw/pharmacies.parquet")
df.head(10)

,nofinesset,nofinessej,rs,rslongue,complrs,numvoie,compvoie,typvoie,voie,lieuditbp,...,cp,commune,telephone,telecopie,dateouv,dateautor,datemaj,wgs84,lat,lng
0,750009193,750009185,PHARMACIE MONTORGUEIL,NaN,NaN,67,NaN,RUE,MONTORGUEIL,NaN,...,75002,PARIS,142368100,142360005,1998-01-05,1942-11-10,2007-12-03,"48.8660446,2.3470265",48.866045,2.347027
1,750009862,750009854,PHARM CROULARD,NaN,NaN,191,NaN,RUE,DU TEMPLE,NaN,...,75003,PARIS,142726797,<NA>,1976-03-12,1942-11-12,2010-08-25,"48.865802,2.360647",48.865802,2.360647
2,750013641,750013633,SELARL PHARMACIE BOSQUET GRENELLE,NaN,PHARMACIE BOSQUET GRENELLE,49,NaN,AVENUE,BOSQUET,NaN,...,75007,PARIS,145513591,145513591,2010-07-01,1943-05-24,2011-07-25,"48.8571082,2.3045687",48.857108,2.304569
3,750015240,750015232,PHARM MARBEUF FRANCOIS 1ER,NaN,NaN,21,NaN,RUE,MARBEUF,39 RUE FRANCOIS 1ER,...,75008,PARIS,147208759,147207369,1986-06-23,1942-10-30,2009-07-03,"48.8685711,2.3034187",48.868571,2.303419
4,750015547,750015521,PHARMACIE ISSOULIE,NaN,NaN,4,NaN,RUE,TREILHARD,NaN,...,75008,PARIS,145632822,<NA>,1982-05-18,1943-05-28,2010-08-25,"48.87680054,2.3153016",48.876801,2.315302
5,750015513,750015505,SELAS GRANDE PHARMACIE BAILLY,NaN,GRANDE PHARMACIE BAILLY,15,NaN,RUE,DE ROME,NaN,...,75008,PARIS,153421010,143934007,2011-05-09,1942-10-21,2011-07-21,"48.8757062,2.32390612",48.875706,2.323906
6,750018046,750018020,PHARMACIE CENTRALE LOUIS BLANC,NaN,NaN,65,NaN,RUE,LOUIS BLANC,NaN,...,75010,PARIS,146074539,146077816,1994-01-28,1943-06-24,2008-10-27,"48.8836395,2.3602574",48.883640,2.360257
7,750018574,750018566,PHARMACIE COURONNES,NaN,NaN,43,NaN,BOULEVARD,DE BELLEVILLE,NaN,...,75011,PARIS,143571607,143571607,2009-07-01,1943-06-30,2009-12-24,"48.86920676,2.3800756",48.869207,2.380076
8,750018731,750018723,PHARMACIE CHAUVEAU,NaN,NaN,98,NaN,RUE,DU CHEMIN VERT,NaN,...,75011,PARIS,147000309,147001361,2007-04-01,1942-12-03,2007-10-10,"48.8611735,2.3815921",48.861173,2.381592
9,750024986,750024960,PHARMACIE RENOIR,NaN,NaN,203,NaN,RUE,RAYMOND LOSSERAND,NaN,...,75014,PARIS,145432211,145432211,1992-01-13,1943-05-05,2009-07-10,"48.8314253,2.3133237",48.831425,2.313324

In [6]:
import pandas as pd

df = pd.read_parquet(r"./raw/plan de voirie.parquet")
df.head(10)

,OBJECTID,NUM_PAVE,IGDS_LEVEL,LIB_LEVEL,LIB_CLASSE,geo_shape,geo_point_2d
0,201825,133G,21,TRANSPORT,NaN,"{""coordinates"": [[2.355696017000305, 48.820648...","48.820641707228745, 2.355690026743711"
1,201854,151G,21,TRANSPORT,NaN,"{""coordinates"": [[2.2925539116883042, 48.83081...","48.830817394205965, 2.292559511087538"
2,201894,193J,21,TRANSPORT,NaN,"{""coordinates"": [[2.405373885476651, 48.877921...","48.87792883476874, 2.4053770841905955"
3,201897,154C,21,TRANSPORT,NaN,"{""coordinates"": [[2.279349104077107, 48.835857...","48.835850671739536, 2.2793447032358625"
4,201903,173B,21,TRANSPORT,NaN,"{""coordinates"": [[2.3126839621584003, 48.89402...","48.89403165510765, 2.3126774919504967"
5,201904,173B,21,TRANSPORT,NaN,"{""coordinates"": [[2.305529956793193, 48.890853...","48.890847195879076, 2.3055367731804695"
6,201912,142C,21,TRANSPORT,NaN,"{""coordinates"": [[2.344144492067862, 48.819424...","48.81943176131715, 2.3441465527689136"
7,201922,184B,21,TRANSPORT,NaN,"{""coordinates"": [[2.3683335048294976, 48.89860...","48.89859769272887, 2.3683338948591546"
8,201929,184B,21,TRANSPORT,NaN,"{""coordinates"": [[2.366460169737078, 48.898538...","48.898530981301846, 2.36646052531536"
9,201944,163E,21,TRANSPORT,NaN,"{""coordinates"": [[2.274746085480351, 48.870281...","48.870285093954166, 2.274735703061824"

In [7]:
import pandas as pd

df = pd.read_parquet(r"./raw/postes-publics-des-bibliotheques.parquet")
df.head(10)

,localisation,type_de_poste,nombre_d_ordinateurs,position
0,Amélie,Poste Adulte et Jeunesse,2,b'\x01\x01\x00\x00\x00\xf9\xdcd\xaf\xd2x\x02@\...
1,Benjamin Rabier,Poste de passage Adulte,1,b'\x01\x01\x00\x00\x00\x15\xad\xdc\x0b\xcc\xfa...
2,Georges Brassens,Poste de passage Adulte,2,"b'\x01\x01\x00\x00\x00\xc9""\xa8uv\x9d\x02@\xce..."
3,Germaine Tillion,Poste Adulte,10,"b""\x01\x01\x00\x00\x00-\x11^q'G\x02@N\x88o\x17..."
4,Vandamme,Poste Jeunesse,3,b'\x01\x01\x00\x00\x00\xe0|\x8f\x9f2\x93\x02@J...
5,Buffon,Poste de passage Adulte,3,b'\x01\x01\x00\x00\x00\xc8^\xef\xfex\xdf\x02@\...
6,Drouot,Catalogue,1,b'\x01\x01\x00\x00\x00\xf4a\x07\xdfE\xb9\x02@-...
7,Glacière - Marina Tsvetaïeva,Catalogue,3,b'\x01\x01\x00\x00\x00\xd0u+\x95\x01\xc1\x02@\...
8,Louise Michel,Poste Adulte et Jeunesse,6,"b'\x01\x01\x00\x00\x00\x04\xc1\x88""I5\x03@\xbc..."
9,Germaine Tillion,Poste Jeunesse,4,"b""\x01\x01\x00\x00\x00-\x11^q'G\x02@N\x88o\x17..."

In [8]:
import pandas as pd

df = pd.read_parquet(r"./raw/secteurs-scolaires-colleges.parquet")
df.head(10)

,id_projet,libelle,annee_scol,zone_commune,etiquette,lib_etab_1,lib_etab_2,lib_etab_3,lib_etab_4,adr_etab_1,adr_etab_2,adr_etab_3,adr_etab_4,st_area_shape,st_perimeter_shape,type_etabl,geo_shape,geo_point_2d
0,COLLEGES (année scolaire 2020/2021),AIME CESAIRE,2020-2021,0,Secteur du collège AIME CESAIRE,AIME CESAIRE,NaN,NaN,NaN,22 RUE PAJOL,NaN,NaN,NaN,3.344510e+05,11538.987331,Collège,b'\x01\x06\x00\x00\x00\x1c\x00\x00\x00\x01\x03...,b'\x01\x01\x00\x00\x00\xf3\x00\x89\x1b\xf8\xe7...
1,COLLEGES (année scolaire 2020/2021),MOZART,2020-2021,0,Secteur du collège MOZART,MOZART,NaN,NaN,NaN,7 RUE JOMARD,NaN,NaN,NaN,2.026897e+05,7404.367718,Collège,b'\x01\x06\x00\x00\x00\x10\x00\x00\x00\x01\x03...,"b'\x01\x01\x00\x00\x00\x0e%""\x05\n\x0b\x03@\x8..."
2,COLLEGES (année scolaire 2020/2021),GUILLAUME BUDE,2020-2021,0,Secteur du collège GUILLAUME BUDE,GUILLAUME BUDE,NaN,NaN,NaN,7 RUE JEAN QUARRE,NaN,NaN,NaN,3.587830e+05,14342.777146,Collège,b'\x01\x06\x00\x00\x00\x1f\x00\x00\x00\x01\x03...,b'\x01\x01\x00\x00\x00\\^\x03\xdb;3\x03@\xbb3~...
3,COLLEGES (année scolaire 2020/2021),CESAR FRANCK,2020-2021,0,Secteur du collège CESAR FRANCK,CESAR FRANCK,NaN,NaN,NaN,5 RUE DE LA JUSSIENNE,NaN,NaN,NaN,3.567674e+05,21156.275757,Collège,b'\x01\x06\x00\x00\x00I\x00\x00\x00\x01\x03\x0...,b'\x01\x01\x00\x00\x00>i[\x06\x8d\xc2\x02@k\x8...
4,COLLEGES (année scolaire 2020/2021),HONORE DE BALZAC,2020-2021,0,Secteur du collège HONORE DE BALZAC,HONORE DE BALZAC,NaN,NaN,NaN,118 BOULEVARD BESSIERES,NaN,NaN,NaN,5.691940e+05,19980.972179,Collège,b'\x01\x06\x00\x00\x00\'\x00\x00\x00\x01\x03\x...,b'\x01\x01\x00\x00\x00\xe5v\x94\x88\x0b\x8d\x0...
5,COLLEGES (année scolaire 2021/2022),SONIA DELAUNAY,2021-2022,0,Secteur du collège SONIA DELAUNAY,SONIA DELAUNAY,NaN,NaN,NaN,14 RUE EURYALE DEHAYNIN,NaN,NaN,NaN,3.218396e+05,14937.427111,Collège,b'\x01\x06\x00\x00\x00\x19\x00\x00\x00\x01\x03...,b'\x01\x01\x00\x00\x00\x9b\xb7\xc4\xc4:\x04\x0...
6,COLLEGES (année scolaire 2021/2022),VALMY,2021-2022,0,Secteur du collège VALMY,VALMY,NaN,NaN,NaN,199 QUAI DE VALMY,NaN,NaN,NaN,4.475100e+05,14500.647004,Collège,b'\x01\x06\x00\x00\x00\x1f\x00\x00\x00\x01\x03...,b'\x01\x01\x00\x00\x00\xc1\x11P\xde\x17\xe6\x0...
7,COLLEGES (année scolaire 2022/2023),VICTOR DURUY,2022-2023,0,Secteur du collège VICTOR DURUY,VICTOR DURUY,NaN,NaN,NaN,33 BOULEVARD DES INVALIDES,NaN,NaN,NaN,1.232058e+06,41867.773837,Collège,b'\x01\x06\x00\x00\x00V\x00\x00\x00\x01\x03\x0...,b'\x01\x01\x00\x00\x00@\x84&\xa6}\x90\x02@\x03...
8,COLLEGES (année scolaire 2022/2023),CHAPTAL,2022-2023,0,Secteur du collège CHAPTAL,CHAPTAL,NaN,NaN,NaN,45 BOULEVARD DES BATIGNOLLES,NaN,NaN,NaN,6.872697e+05,26940.994055,Collège,b'\x01\x06\x00\x00\x00?\x00\x00\x00\x01\x03\x0...,b'\x01\x01\x00\x00\x00\x9c}-\xa3S{\x02@\xe0C\x...
9,COLLEGES (année scolaire 2022/2023),GEORGES BRAQUE,2022-2023,0,Secteur du collège GEORGES BRAQUE,GEORGES BRAQUE,NaN,NaN,NaN,91 RUE BRILLAT-SAVARIN,NaN,NaN,NaN,6.718816e+05,25706.624994,Collège,b'\x01\x06\x00\x00\x004\x00\x00\x00\x01\x03\x0...,b'\x01\x01\x00\x00\x00\xc9\xae\rI9\xbc\x02@\x9...

In [9]:
import pandas as pd

df = pd.read_parquet(r"./raw/secteurs-scolaires-maternelles.parquet")
df.head(10)

,id_projet,libelle,annee_scol,zone_commune,etiquette,lib_etab_1,lib_etab_2,lib_etab_3,lib_etab_4,adr_etab_1,adr_etab_2,adr_etab_3,adr_etab_4,type_etabl,geo_shape,geo_point_2d,st_area_shape,st_perimeter_shape
0,MATERNELLES (année scolaire 2020/2021),BIDASSOA (21) MAT,2020-2021,0,Secteur de l'école 21 RUE DE LA BIDASSOA,BIDASSOA (21) MAT,NaN,NaN,NaN,21 RUE DE LA BIDASSOA,NaN,NaN,NaN,NaN,b'\x01\x06\x00\x00\x00\x14\x00\x00\x00\x01\x03...,b'\x01\x01\x00\x00\x00B\xd1\x07;G(\x03@\xd5\x8...,97985.387347,6580.143521
1,MATERNELLES (année scolaire 2020/2021),JEAN MENANS (2) MAT,2020-2021,0,Secteur de l'école 2 RUE JEAN MENANS,JEAN MENANS (2) MAT,NaN,NaN,NaN,2 RUE JEAN MENANS,NaN,NaN,NaN,NaN,b'\x01\x06\x00\x00\x00\x0b\x00\x00\x00\x01\x03...,b'\x01\x01\x00\x00\x00!\xe8\x844\xb9\t\x03@\xf...,80302.967029,5163.035554
2,MATERNELLES (année scolaire 2020/2021),ROQUETTE (144) MAT,2020-2021,0,Secteur de l'école 144 RUE DE LA ROQUETTE,ROQUETTE (144) MAT,NaN,NaN,NaN,144 RUE DE LA ROQUETTE,NaN,NaN,NaN,NaN,b'\x01\x06\x00\x00\x00\x1c\x00\x00\x00\x01\x03...,b'\x01\x01\x00\x00\x00.\x8d\xb0\xa9v\x12\x03@W...,109981.794413,7417.070188
3,MATERNELLES (année scolaire 2020/2021),PERLE (7) MAT,2020-2021,0,Secteur de l'école 7 RUE DE LA PERLE,PERLE (7) MAT,NaN,NaN,NaN,7 RUE DE LA PERLE,NaN,NaN,NaN,NaN,b'\x01\x06\x00\x00\x00\x1b\x00\x00\x00\x01\x03...,b'\x01\x01\x00\x00\x00\x1c\r\x12\xf7\xe4\xe1\x...,256477.819153,11474.563809
4,MATERNELLES (année scolaire 2020/2021),JEANNE D'ARC (32) MAT,2020-2021,0,Secteur de l'école 32 PLACE JEANNE D'ARC,JEANNE D'ARC (32) MAT,NaN,NaN,NaN,32 PLACE JEANNE D'ARC,NaN,NaN,NaN,NaN,b'\x01\x06\x00\x00\x00\t\x00\x00\x00\x01\x03\x...,b'\x01\x01\x00\x00\x00&\xfe4\xba\xd6\xf4\x02@Z...,53089.544031,3712.634006
5,MATERNELLES (année scolaire 2020/2021),PAJOL (11) POLY,2020-2021,0,Secteur de l'école 11 bis RUE PAJOL,PAJOL (11) POLY,NaN,NaN,NaN,11 bis RUE PAJOL,NaN,NaN,NaN,NaN,b'\x01\x06\x00\x00\x00\x07\x00\x00\x00\x01\x03...,"b""\x01\x01\x00\x00\x00\xa4\xc6m\xe6\x80\xe4\x0...",44464.216296,2744.494696
6,MATERNELLES (année scolaire 2020/2021),ALESIA (190) MAT,2020-2021,0,Secteur de l'école 190 RUE D' ALESIA,ALESIA (190) MAT,NaN,NaN,NaN,190 RUE D' ALESIA,NaN,NaN,NaN,NaN,b'\x01\x06\x00\x00\x00\x12\x00\x00\x00\x01\x03...,b'\x01\x01\x00\x00\x00)rQ\x193\x86\x02@L( S\xa...,89558.341791,6333.070435
7,MATERNELLES (année scolaire 2020/2021),RAPP (28) MAT,2020-2021,0,Secteur de l'école 28 AVENUE RAPP,RAPP (28) MAT,NaN,NaN,NaN,28 AVENUE RAPP,NaN,NaN,NaN,NaN,b'\x01\x06\x00\x00\x000\x00\x00\x00\x01\x03\x0...,b'\x01\x01\x00\x00\x00\xa0\x80\x1a\x07\xcef\x0...,291516.678878,16113.860951
8,MATERNELLES (année scolaire 2020/2021),PERCHAMPS (38) MAT,2020-2021,0,Secteur de l'école 38 RUE DES PERCHAMPS,PERCHAMPS (38) MAT,NaN,NaN,NaN,38 RUE DES PERCHAMPS,NaN,NaN,NaN,NaN,b'\x01\x06\x00\x00\x00*\x00\x00\x00\x01\x03\x0...,b'\x01\x01\x00\x00\x00\xe7\n\xf6IO$\x02@\x94\x...,199121.865694,12778.821525
9,MATERNELLES (année scolaire 2020/2021),ECLUSES ST MARTIN (28) MAT,2020-2021,0,Secteur de l'école 28 RUE DES ECLUSES SAINT-MA...,ECLUSES ST MARTIN (28) MAT,NaN,NaN,NaN,28 RUE DES ECLUSES SAINT-MARTIN,NaN,NaN,NaN,NaN,b'\x01\x06\x00\x00\x00\x10\x00\x00\x00\x01\x03...,b'\x01\x01\x00\x00\x00\x93\xa3\xaf1V\xe9\x02@....,184277.914854,7952.482131